# ExternalSecret to sync all secrets from Infisical root project
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-root-sync
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical-root
  target:
    name: {{ .Values.target.secretName }}
  dataFrom:
    - find:
        name:
          regexp: .*
