# ExternalSecret to sync all secrets from Infisical root project
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}
  target:
    name: {{ .Values.target.secretName }}
  dataFrom:
    - find:
        name:
          regexp: .*
