# Universal Auth credentials for ESO
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  clientId: {{ .Values.credentials.clientId }}
  clientSecret: {{ .Values.credentials.clientSecret }}
