# Namespace
namespace: ""

# PostgreSQL port
postgres:
  port: 5432

# Redis port
redis:
  port: 6379

# Traefik namespace for NetworkPolicy
traefik:
  namespace: ""

# External Secrets namespace for NetworkPolicy
externalSecrets:
  namespace: ""
