# Namespace
namespace: ""

# DaemonSet name
daemonsetName: ""

# Traefik image
image: traefik:v3.6.2

# IngressClass
ingressClass: ""

# EntryPoints
entryPoints:
  web: ""
  websecure: ""

# VPN IP whitelist
vpnIps:
  - "1.2.3.4/32"

# Dashboard Ingress
dashboard:
  domain: ""
  secretName: ""
  clusterIssuer: ""
  # VPN-only middleware (restrict access to VPN IPs)
  vpnOnlyEnabled: true
