# Namespace
namespace: gitlab

# GitLab image
image: gitlab/gitlab-ce:16.11.10-ce.0

# Storage
storageClass: lh-major-multi-best-effort
storageClassLogs: lh-major-worker-multi-best-effort
storageConfigSize: 1Gi
storageDataSize: 20Gi
storageLogsSize: 5Gi

# SSH port external
sshPortExternal: 3714

# MinIO internal service URL
minioServiceUrl: "http://svc-gitlab-minio:9000"

# MinIO registry bucket name
minioRegistryBucketName: "registry"

# MinIO registry keys secret name (created by ESO)
minioRegistryKeysSecretName: "secret-gitlab-minio-registry-keys"

# Ingress settings (for configmap URLs)
ingress:
  domain: ""
  registryDomain: ""
  pagesDomain: ""

# HAProxy settings for SSH
haproxy:
  namespace: ""
  ingressClass: ""

# Resources
resources:
  requests:
    memory: 2G
  limits:
    memory: 3G
