apiVersion: v1
kind: Service
metadata:
  name: svc-gitlab-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-postgresql
    app.kubernetes.io/instance: gitlab-postgresql-{{ .Values.namespace }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: gitlab
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: gitlab-postgresql
    app.kubernetes.io/instance: gitlab-postgresql-{{ .Values.namespace }}
