# DO NOT CHANGE - hardcoded in templates/longhorn.yaml
namespace: "longhorn-system"

# Ingress settings
ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true

# Traefik settings for NetworkPolicy
traefik:
  namespace: ""

# S3 Backup credentials
s3Backup:
  accessKeyId: ""
  secretAccessKey: ""
  endpoint: ""
