# Namespace
namespace: ""

# Redis settings (redis-stack)
redis:
  image: ""
  port: 6379
  storageClass: ""
  storageSize: "2Gi"
  # REDIS_ARGS - full args string (set via playbook)
  # Example: "--save 60 1 --requirepass <password>"
  args: ""
  # REDIS_PASSWORD - password only (for connection string)
  password: ""
