apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-redis
    app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: gitlab
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gitlab-redis
      app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitlab-redis
        app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: gitlab
        app.kubernetes.io/managed-by: Helm
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: {{ .Values.image }}
          env:
            - name: REDIS_ARGS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: redis_args
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-gitlab-redis
