apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-redis
    app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: gitlab
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
