apiVersion: v1
kind: Service
metadata:
  name: svc-gitlab-redis
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-redis
    app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: gitlab
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: gitlab-redis
    app.kubernetes.io/instance: gitlab-redis-{{ .Values.namespace }}
