apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-minio
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-minio
    app.kubernetes.io/component: object-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
