namespace: ""
clusterDomain: ""

ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true

traefik:
  namespace: ""

vault:
  namespace: ""
  kvMountPath: ""

eso:
  vaultPath: ""
  s3SecretName: ""
  saName: ""
  roleName: ""
  secretStoreName: ""
  externalSecretName: ""
  targetSecretName: ""

azList: []
