namespace: ""

ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true

traefik:
  namespace: ""

s3Backup:
  accessKeyId: ""
  secretAccessKey: ""
  endpoint: ""
