# Namespace
namespace: "argocd"

# Git-ops AppProject and Application settings
gitOps:
  project:
    sourceRepos:
      - "*"
    destinations:
      - name: "*"
        namespace: "*"
        server: "*"
  app:
    repoURL: ""
    targetRevision: "master"
    path: "argocd-system"
    destinationServer: "https://kubernetes.default.svc"
  retry:
    limit: 5
    backoff:
      duration: "20s"
      factor: 1
      maxDuration: "30s"
