# =============================================================================
# CLUSTER ISSUER FOR LET'S ENCRYPT
# =============================================================================

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.server }}
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.clusterIssuer.ingressClass }}
            ingressTemplate:
              metadata:
                annotations:
                  "kubernetes.io/ingress.class": "{{ .Values.clusterIssuer.ingressClass }}"
                  "traefik.ingress.kubernetes.io/router.entrypoints": "{{ .Values.clusterIssuer.traefikEntrypoint }}"
            podTemplate:
              metadata:
                labels:
                  app.kubernetes.io/name: acme-solver
                  app.kubernetes.io/instance: traefik-master
                  app.kubernetes.io/component: acme-http01-solver
                  app.kubernetes.io/managed-by: cert-manager
