# Namespace
namespace: argocd

# Ingress settings
ingress:
  uiDomain: ""
  rpcDomain: ""
  ingressClass: ""
  secretName: ""
  entrypoint: ""
  clusterIssuer: ""
  vpnOnlyEnabled: true

# Traefik settings for NetworkPolicy and middlewares
traefik:
  namespace: ""

# GitLab settings for git-ops
gitlab:
  namespace: ""
  internalUrl: "ssh://git@svc-gitlab.gitlab.svc.cluster.local:22/server/git-ops.git"
  sshPrivateKey: ""

