# Namespace
namespace: "argocd"

# Ingress settings
ingress:
  uiDomain: ""
  rpcDomain: ""
  ingressClass: ""
  secretName: ""
  entrypoint: ""
  clusterIssuer: ""
  vpnOnlyEnabled: true

# Traefik settings for NetworkPolicy and middlewares
traefik:
  namespace: ""

# GitLab namespace (for NetworkPolicy)
gitlab:
  namespace: ""
