# Namespace
namespace: "argocd"

# Ingress settings
ingress:
  uiDomain: ""
  rpcDomain: ""
  ingressClass: ""
  secretName: ""
  entrypoint: ""
  clusterIssuer: ""
  vpnOnlyEnabled: true

# Traefik settings for NetworkPolicy and middlewares
traefik:
  namespace: ""

# GitLab settings for git-ops
gitlab:
  namespace: ""

# Git-ops AppProject and Application settings
gitOps:
  project:
    sourceRepos:
      - "*"
    destinations:
      - name: "*"
        namespace: "*"
        server: "*"
  app:
    repoURL: "ssh://git@svc-gitlab.gitlab.svc.cluster.local:22/server/git-ops.git"
    targetRevision: "master"
    path: "argocd-system"
    destinationServer: "https://kubernetes.default.svc"
  retry:
    limit: 5
    backoff:
      duration: "20s"
      factor: 1
      maxDuration: "30s"

# ESO settings for SSH repo-creds secret
eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: "eso-secret"
  secrets: []

# Vault settings (for SecretStore endpoint)
vault:
  namespace: "vault"

clusterDomain: "cluster.local"

