# Namespace
namespace: ns-gitlab

# MinIO image
image: minio/minio:RELEASE.2025-04-22T22-12-26Z

# Storage
storageClass: lh-major-worker-multi-best-effort
storageSize: 30Gi

# Root credentials secret name (created by ESO)
rootSecretName: secret-gitlab-minio
