apiVersion: v1
kind: Secret
metadata:
  name: secret-gitlab-minio
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-user: {{ .Values.rootUser | b64enc }}
  root-password: {{ .Values.rootPassword | b64enc }}

