# MinIO configuration
namespace: ns-gitlab

image: minio/minio:latest

# Storage
storageClass: lh-major-single-best-effort
storageSize: 50Gi

# Root credentials secret (from ESO)
rootSecretName: ""

# Resources
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
