{{- if .Values.minio.enabled }}
# =============================================================================
# INGRESS FOR MINIO CONSOLE (optional)
# =============================================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ir-gitlab-minio-console
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.minio.clusterIssuer }}
spec:
  entryPoints:
    - {{ .Values.minio.entrypoint }}
  routes:
    - match: Host(`{{ .Values.minio.domain }}`)
      kind: Rule
      services:
        - name: svc-gitlab-minio
          port: 9001
  tls:
    secretName: {{ .Values.minio.secretName }}
{{- end }}
