apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lh-gitlab-config-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageConfigSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lh-gitlab-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageDataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lh-gitlab-log-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassLogs }}
  resources:
    requests:
      storage: {{ .Values.storageLogsSize }}

