# PostgreSQL configuration
namespace: ns-gitlab

image: postgres:16-alpine

# Storage
storageClass: lh-major-multi-best-effort
storageSize: 20Gi

# Credentials secret (from ESO)
credentialsSecretName: ""
