# =============================================================================
# SECRET STORE FOR GITLAB MINIO SECRETS
# =============================================================================

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.gitlabMinio.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: http://vault.{{ .Values.vault.namespace }}.svc.{{ .Values.dnsDomain }}:8200
      path: {{ .Values.gitlabMinio.kvEnginePath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.gitlabMinio.roleName }}
          serviceAccountRef:
            name: {{ .Values.gitlabMinio.saName }}
