# =============================================================================
# SERVICE ACCOUNTS FOR VAULT AUTHENTICATION
# =============================================================================

---
# ServiceAccount for GitLab secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gitlab.saName }}
  namespace: {{ .Values.namespace }}

---
# ServiceAccount for GitLab MinIO secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gitlabMinio.saName }}
  namespace: {{ .Values.namespace }}
