# Namespace
namespace: ns-gitlab

# MinIO image
image: minio/minio:RELEASE.2025-04-22T22-12-26Z

# Storage
storageClass: lh-major-worker-multi-best-effort
storageSize: 30Gi

# Root credentials (base64 encoded in secret)
rootUser: admin
rootPassword: ""

# Ingress settings
ingress:
  ingressClass: traefik-master-lb
  entrypoint: traefik-websecure
  domain: gitlab-minio.domain.com
  apiDomain: gitlab-minio-api.domain.com
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik settings for middlewares
traefik:
  namespace: ""

