# =============================================================================
# SERVICE ACCOUNT FOR ESO ROOT AUTHENTICATION
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.esoRoot.saName }}
  namespace: {{ .Values.vault.namespace }}
