# Namespace
namespace: "argocd"

# GitLab internal SSH URL (used in repo-creds Secret template)
gitlab:
  internalUrl: ""

# ESO settings for SSH repo-creds secret
eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: "eso-secret"
  secrets: []
  # Example:
  # - external_secret_name: "eso-argocd-repo-creds"
  #   target_secret_name: "git-ops-root-key-internal"
  #   vault_path: "/argocd/repo-creds"
  #   refresh_interval: "1m"

# Vault settings (for SecretStore endpoint)
vault:
  namespace: "vault"

clusterDomain: "cluster.local"
