namespace: ""

ingress:
  uiDomain: ""
  rpcDomain: ""
  ingressClass: ""
  entrypoint: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true

traefik:
  namespace: ""

gitlab:
  namespace: ""
