# Namespace
namespace: ns-gitlab

# DNS domain for internal service resolution
clusterDomain: cluster.local

# Vault settings
vault:
  namespace: ns-vault

# External Secrets settings
externalSecrets:
  namespace: ns-external-secrets

# Traefik settings for NetworkPolicy
traefik:
  namespace: ns-traefik-master

# HAProxy settings for NetworkPolicy
haproxy:
  namespace: ns-haproxy-master

# GitLab v2 ESO settings (all secrets in one)
gitlabV2Eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: "secret"
  secrets: []
  # Example:
  # - external_secret_name: "eso-gitlab-postgresql"
  #   target_secret_name: "secret-gitlab-postgresql"
  #   vault_path: "/ns-gitlab/postgresql/credentials"
  #   refresh_interval: "1m"
