# =============================================================================
# EXTERNAL SECRET FOR LONGHORN S3 BACKUP CREDENTIALS SYNC
# =============================================================================

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.eso.externalSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.eso.secretStoreName }}
  target:
    name: {{ .Values.eso.targetSecretName }}
  dataFrom:
    - extract:
        key: {{ .Values.vault.kvMountPath }}/data/{{ .Values.eso.vaultPath }}/{{ .Values.eso.s3SecretName }}
