# =============================================================================
# LONGHORN UI INGRESS
# =============================================================================

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.secretName }}
  dnsNames:
    - {{ .Values.ingress.domain }}
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-longhorn-ui-https
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingressClass }}"
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .Values.ingress.entrypoint }}"
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.ingress.vpnOnlyEnabled }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-vpn-only@kubernetescrd"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80

