# ClusterIssuer settings
clusterIssuer:
  name: ""
  email: ""
  # ACME server (prod or staging)
  # Prod: https://acme-v02.api.letsencrypt.org/directory
  # Staging: https://acme-staging-v02.api.letsencrypt.org/directory
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: cluster-issuer-acme-prod-account-key
  # HTTP01 solver settings
  ingressClass: ""
  traefikEntrypoint: ""
