# Namespace
namespace: ""

# Ingress settings
ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ""
