apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-test
  namespace: ns-nginx-helm-test
  annotations:
    argocd.argoproj.io/sync-options: Force=true
spec:
  replicas: 2
  selector:
    matchLabels:
      rs-ctrl-key: nginx-helm-test
  template:
    metadata:
      labels:
        rs-ctrl-key: nginx-helm-test
        svc-route-key: nginx-helm-test
    spec:
      containers:
        - name: nginx-helm-test
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: web-htpp
              containerPort: 80
