apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-helm-test-http
  namespace: ns-nginx-helm-test
  annotations:
    kubernetes.io/ingress.class: "traefik-master-lb"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  rules:
    - host: nginx-helm-test.my-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nginx-helm-test
                port:
                  number: 80