apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-helm-test
  namespace: ns-nginx-helm-test
spec:
  selector:
    svc-route-key: nginx-helm-test
  type: ClusterIP
  ports:
    - name: nginx-helm-test-http
      port: 80 # Эти два поля, всегда ставятся одинаковыми
      targetPort: 80 #
      protocol: TCP