# Namespace
namespace: gitlab

# DNS domain for Vault service URL
dnsDomain: cluster.local

# Vault settings
vault:
  namespace: vault
  kvMountPath: secret

# GitLab ESO settings
gitlab:
  saName: gitlab-vault-auth
  roleName: gitlab-role
  secretStoreName: vault-gitlab
  rootSecretName: eso-gitlab-root

# GitLab MinIO ESO settings
gitlabMinio:
  saName: gitlab-minio-vault-auth
  roleName: gitlab-minio-role
  secretStoreName: vault-gitlab-minio
  rootSecretName: eso-gitlab-minio-root
  registrySecretName: eso-gitlab-minio-registry
