# Redis configuration
namespace: ns-gitlab

image: redis/redis-stack-server:latest

# Credentials secret (from ESO)
credentialsSecretName: ""

# Storage configuration
storageClass: ""
storageSize: "1Gi"
