# =============================================================================
# SERVICE ACCOUNT FOR VAULT AUTHENTICATION
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gitlabEso.saName }}
  namespace: {{ .Values.namespace }}
