# =============================================================================
# CUSTOM LONGHORN STORAGE CLASSES - PER AZ
# Generated for each AZ in azList with lh-az selector
# =============================================================================

{{- range $az := .Values.azList }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-single-strict-local"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "strict-local"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-minor-worker-single-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-minor-worker-multi-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-minor-worker-three-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-single-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-worker-single-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-manager-single-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-multi-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-three-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-worker-multi-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-worker-three-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-manager-multi-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ $az }}-major-manager-three-best-effort"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,{{ $az }}"
{{- end }}
