# =============================================================================
# CUSTOM LONGHORN STORAGE CLASSES - PER AZ
# Generated for each AZ in azList with lh-az selector
# =============================================================================

{{- range $az := .Values.azList }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-single-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "strict-local"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-minor-worker-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-minor-worker-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-minor-worker-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-worker-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-manager-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-worker-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-worker-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-manager-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,lh-az-{{ $az }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $az }}-lh-major-manager-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager,lh-az-{{ $az }}"
{{- end }}
