apiVersion: v1
kind: Service
metadata:
  name: svc-gitlab
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app-key: gitlab
    app-env: prod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
    - port: 81
      targetPort: 81
      protocol: TCP
      name: registry
    - port: 82
      targetPort: 82
      protocol: TCP
      name: pages
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
