---
# Default project - DISABLED (no permissions)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  clusterResourceBlacklist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: "*"
      kind: "*"