namespace: ""
clusterDomain: ""

ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: true

traefik:
  namespace: ""

vault:
  namespace: ""
  kvMountPath: ""

eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  kvEnginePath: ""
  secrets: []

azList: []
