# Namespace
namespace: ns-gitlab

# SSH port for HAProxy
sshPortExternal: 3714

# GitLab settings
gitlab:
  ingressClass: traefik
  entrypoint: websecure
  domain: ""
  registryDomain: ""
  pagesDomain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# MinIO settings (Console + API ingress)
minio:
  ingressClass: traefik
  entrypoint: websecure
  consoleDomain: ""   # Console domain (UI)
  apiDomain: ""       # API domain (S3)
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ns-traefik-master

# HAProxy settings for SSH TCP ingress
haproxy:
  namespace: ns-haproxy-master
  ingressClass: haproxy
