# Namespace
namespace: ""

# DNS domain for internal service resolution
clusterDomain: ""

# Vault settings
vault:
  kvMountPath: ""

# Ingress settings
ingress:
  ingressClass: ""
  entrypoint: ""
  domain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik namespace for middleware
traefik:
  namespace: ""

# ESO settings
eso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  secrets: []
