# Namespace
namespace: haproxy-master

# IngressClass
ingressClass: haproxy-master-lb

# Global config
global:
  maxconn: 10000
  nbthread: 2
  bufsize: 32768
  maxrewrite: 8192
  rcvbuf_client: 32768
  rcvbuf_server: 32768
  sndbuf_client: 32768
  sndbuf_server: 32768
  maxaccept: 32
  runqueue_depth: 128

# Defaults config
defaults:
  mode: tcp
  client_timeout: 3600000
  server_timeout: 3600000
  connect_timeout: 5000
  queue_timeout: 60000
  retries: 5
  check_timeout: 5000
  # Keepalive
  clitcpka_idle: 60000
  clitcpka_intvl: 10000
  clitcpka_cnt: 3
  srvtcpka_idle: 60000
  srvtcpka_intvl: 10000
  srvtcpka_cnt: 3
