# Namespace
namespace: gitlab

# GitLab Ingress settings
gitlab:
  ingressClass: traefik-master-lb
  entrypoint: traefik-websecure
  domain: ""
  registryDomain: ""
  pagesDomain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# MinIO Ingress settings
minio:
  ingressClass: traefik-master-lb
  entrypoint: traefik-websecure
  domain: ""
  apiDomain: ""
  clusterIssuer: ""
  secretName: ""
  vpnOnlyEnabled: false

# Traefik settings for middlewares
traefik:
  namespace: ""
