apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-postgresql
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
