apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-gitlab-minio # Никак не связано с secretName. Просто - одинаковые названия
  namespace: ns-gitlab
spec:
  secretName: cert-gitlab-minio # Название секрета, где лежит сертификат. Используется в Traefik.IngressRoute
  dnsNames:
    - "gitlab-minio.my-domain.com"
    - "gitlab-minio-api.my-domain.com"
  issuerRef:
    name: cluster-issuer-acme-prod # Название объекта CLUSTER_ISSUER
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitlab-minio-https
  namespace: ns-gitlab
  annotations:
    kubernetes.io/ingress.class: "traefik-master-lb"
    traefik.ingress.kubernetes.io/router.entrypoints: "traefik-websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik-master-lb
  tls:
    - hosts:
        - gitlab-minio.my-domain.com
        - gitlab-minio-api.my-domain.com
      secretName: cert-gitlab-minio
  rules:
    - host: gitlab-minio.my-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-gitlab-minio
                port:
                  number: 9001
    - host: gitlab-minio-api.my-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-gitlab-minio
                port:
                  number: 9000
