# DNS domain for internal service resolution
clusterDomain: ""

# Vault settings
vault:
  namespace: ""
  kvMountPath: ""  # DO NOT CHANGE - standard path for KV secrets engine
  selfCredsPath: ""  # Path where Vault stores its own credentials

# ESO root authentication settings
selfEso:
  policyName: ""
  roleName: ""
  saName: ""

# SecretStore settings
secretStore:
  name: ""

# ExternalSecret settings
externalSecret:
  name: ""

# Target Kubernetes Secret
targetSecret:
  name: ""
