# =============================================================================
# SERVICE ACCOUNT FOR ESO ROOT AUTHENTICATION
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.selfEso.saName }}
  namespace: {{ .Values.vault.namespace }}
