# =============================================================================
# CUSTOM LONGHORN STORAGE CLASSES
# =============================================================================

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-single-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "strict-local"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-minor-worker-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-minor-worker-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-minor-worker-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-minor-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-worker-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-manager-single-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-worker-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-worker-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-worker"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-manager-multi-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-major-manager-three-best-effort
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataLocality: "best-effort"
  fsType: "ext4"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  nodeSelector: "lh-major-volume,lh-manager"

