# Namespace
namespace: ns-gitlab

# DNS domain for internal service resolution
clusterDomain: ""

gitlab:
  sshPortExternal: 3714
  # VPN settings for SSH NetworkPolicy
  vpnOnlyEnabled: false
  vpnIps: []

# Traefik settings for NetworkPolicy
traefik:
  namespace: ns-traefik-master

# HAProxy settings for NetworkPolicy
haproxy:
  namespace: ns-haproxy-master

# Vault settings for NetworkPolicy and SecretStore
vault:
  namespace: ns-vault
  kvMountPath: ""

# External Secrets settings for NetworkPolicy
externalSecrets:
  namespace: ns-external-secrets

# GitLab ESO settings
gitlabEso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  secrets: []

# GitLab MinIO ESO settings
gitlabMinioEso:
  saName: ""
  roleName: ""
  secretStoreName: ""
  secrets: []
