# Namespace
namespace: ns-gitlab

gitlab:
  sshPortExternal: 3714
  # VPN settings for SSH NetworkPolicy
  vpnOnlyEnabled: false
  vpnIps: []

# Traefik settings for NetworkPolicy
traefik:
  namespace: ns-traefik-master

# HAProxy settings for NetworkPolicy
haproxy:
  namespace: ns-haproxy-master

# Vault settings for NetworkPolicy
vault:
  namespace: ns-vault

# External Secrets settings for NetworkPolicy
externalSecrets:
  namespace: ns-external-secrets
