# =============================================================================
# LONGHORN S3 BACKUP CREDENTIALS
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-backup-creds
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Backup.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Backup.secretAccessKey | b64enc }}
  AWS_ENDPOINTS: {{ .Values.s3Backup.endpoint | b64enc }}

