# =============================================================================
# SECRET STORE FOR GITLAB SECRETS
# =============================================================================

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.gitlabEso.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: http://vault.{{ .Values.vault.namespace }}.svc.{{ .Values.clusterDomain }}:8200
      path: {{ .Values.vault.kvMountPath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.gitlabEso.roleName }}
          serviceAccountRef:
            name: {{ .Values.gitlabEso.saName }}
