# =============================================================================
# SECRET STORE FOR GITLAB MINIO SECRETS
# =============================================================================

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.gitlabMinioEso.secretStoreName }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: http://vault.{{ .Values.vault.namespace }}.svc.{{ .Values.clusterDomain }}:8200
      path: {{ .Values.gitlabMinioEso.kvEnginePath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.gitlabMinioEso.roleName }}
          serviceAccountRef:
            name: {{ .Values.gitlabMinioEso.saName }}
