# =============================================================================
# EXTERNAL SECRETS FOR GITLAB MINIO (from Vault)
# =============================================================================

{{- range $secret := .Values.gitlabMinioEso.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ $secret.refresh_interval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.gitlabMinioEso.secretStoreName }}
  target:
    name: {{ $secret.target_secret }}
  dataFrom:
    - extract:
        key: {{ $.Values.gitlabMinioEso.kvEnginePath }}/data{{ $secret.vault_path }}
{{- end }}
